"""core identity foundation

Revision ID: e54a7134967b
Revises:
Create Date: 2026-09-14 17:52:16.006222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

resource_status_enum = postgresql.ENUM(
    "ACTIVE",
    "DISABLED",
    name="resource_status",
    create_type=False,
)

idempotency_state_enum = postgresql.ENUM(
    "IN_PROGRESS",
    "COMPLETED",
    "FAILED",
    name="idempotency_state",
    create_type=False,
)
# revision identifiers, used by Alembic.
revision: str = "e54a7134967b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()

    resource_status_enum.create(bind, checkfirst=True)
    idempotency_state_enum.create(bind, checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            resource_status_enum,
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("name", name=op.f("uq_tenants_name")),
    )
    op.create_table(
        "admin_users",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            resource_status_enum,
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_admin_users_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_admin_users_tenant_id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_admin_users_tenant_name"),
    )
    op.create_index(
        "ix_admin_users_tenant_status",
        "admin_users",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "applications",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            resource_status_enum,
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_applications_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_applications_tenant_id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_applications_tenant_name"),
    )
    op.create_index(
        "ix_applications_tenant_status",
        "applications",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "admin_tokens",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            resource_status_enum,
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "admin_user_id"],
            ["admin_users.tenant_id", "admin_users.id"],
            name=op.f("fk_admin_tokens_tenant_id_admin_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_admin_tokens_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_admin_tokens_token_hash")),
    )
    op.create_index(
        "ix_admin_tokens_tenant_user_status",
        "admin_tokens",
        ["tenant_id", "admin_user_id", "status"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            resource_status_enum,
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "application_id"],
            ["applications.tenant_id", "applications.id"],
            name=op.f("fk_api_keys_tenant_id_applications"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
    )
    op.create_index(
        "ix_api_keys_tenant_application_status",
        "api_keys",
        ["tenant_id", "application_id", "status"],
        unique=False,
    )
    op.create_table(
        "idempotency_records",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_key", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=128), nullable=False),
        sa.Column(
            "state",
            idempotency_state_enum,
            nullable=False,
        ),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column(
            "response_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "admin_user_id"],
            ["admin_users.tenant_id", "admin_users.id"],
            name=op.f("fk_idempotency_records_tenant_id_admin_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint(
            "tenant_id",
            "admin_user_id",
            "endpoint_key",
            "idempotency_key",
            name="uq_idempotency_scope_key",
        ),
    )
    op.create_index(
        "ix_idempotency_expires_at", "idempotency_records", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_idempotency_expires_at", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index("ix_api_keys_tenant_application_status", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("ix_admin_tokens_tenant_user_status", table_name="admin_tokens")
    op.drop_table("admin_tokens")
    op.drop_index("ix_applications_tenant_status", table_name="applications")
    op.drop_table("applications")
    op.drop_index("ix_admin_users_tenant_status", table_name="admin_users")
    op.drop_table("admin_users")
    op.drop_table("tenants")
    bind = op.get_bind()

    idempotency_state_enum.drop(bind, checkfirst=True)
    resource_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
